### ISSUE TITLE
Mac x86-64: code runs, but does not visualize.

### ISSUE THREAD

**Issue by jbongard** [robodiff/robodiff#2]
**(public-robodiff) ip0af5c808:robodiff jbongard$ python visualization/visualizer_gl_taichi_free.py** 

Traceback (most recent call last):
  File "/Users/jbongard/anaconda3/envs/public-robodiff/lib/python3.7/site-packages/OpenGL/platform/darwin.py", line 38, in GL
    mode=ctypes.RTLD_GLOBAL 
  File "/Users/jbongard/anaconda3/envs/public-robodiff/lib/python3.7/site-packages/OpenGL/platform/ctypesloader.py", line 36, in loadLibrary
    return _loadLibraryWindows(dllType, name, mode)
  File "/Users/jbongard/anaconda3/envs/public-robodiff/lib/python3.7/site-packages/OpenGL/platform/ctypesloader.py", line 89, in _loadLibraryWindows
    return dllType( name, mode )
  File "/Users/jbongard/anaconda3/envs/public-robodiff/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ("dlopen(OpenGL, 0x000A): tried: 'OpenGL' (no such file), '/System/Volumes/Preboot/Cryptexes/OSOpenGL' (no such file), '/Users/jbongard/anaconda3/envs/public-robodiff/lib/python3.7/lib-dynload/../../OpenGL' (no such file), '/Users/jbongard/anaconda3/envs/public-robodiff/bin/../lib/OpenGL' (no such file), '/usr/lib/OpenGL' (no such file, not in dyld cache), 'OpenGL' (no such file), '/usr/local/lib/OpenGL' (no such file), '/usr/lib/OpenGL' (no such file, not in dyld cache)", 'OpenGL', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "visualization/visualizer_gl_taichi_free.py", line 8, in <module>
    from glumpy.transforms.viewport import Viewport
  File "/Users/jbongard/anaconda3/envs/public-robodiff/lib/python3.7/site-packages/glumpy/__init__.py", line 7, in <module>
    from . import app
  File "/Users/jbongard/anaconda3/envs/public-robodiff/lib/python3.7/site-packages/glumpy/app/__init__.py", line 14, in <module>
    from glumpy import gl
  File "/Users/jbongard/anaconda3/envs/public-robodiff/lib/python3.7/site-packages/glumpy/gl.py", line 30, in <module>
    from OpenGL import contextdata
  File "/Users/jbongard/anaconda3/envs/public-robodiff/lib/python3.7/site-packages/OpenGL/contextdata.py", line 21, in <module>
    from OpenGL import platform
  File "/Users/jbongard/anaconda3/envs/public-robodiff/lib/python3.7/site-packages/OpenGL/platform/__init__.py", line 56, in <module>
    _load()
  File "/Users/jbongard/anaconda3/envs/public-robodiff/lib/python3.7/site-packages/OpenGL/platform/__init__.py", line 53, in _load
    plugin.install(globals())
  File "/Users/jbongard/anaconda3/envs/public-robodiff/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 97, in install
    namespace[ name ] = getattr(self,name,None)
  File "/Users/jbongard/anaconda3/envs/public-robodiff/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 15, in __get__
    value = self.fget( obj )
  File "/Users/jbongard/anaconda3/envs/public-robodiff/lib/python3.7/site-packages/OpenGL/platform/darwin.py", line 62, in GetCurrentContext
    return self.CGL.CGLGetCurrentContext 
  File "/Users/jbongard/anaconda3/envs/public-robodiff/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 15, in __get__
    value = self.fget( obj )
  File "/Users/jbongard/anaconda3/envs/public-robodiff/lib/python3.7/site-packages/OpenGL/platform/darwin.py", line 45, in CGL
    def CGL(self): return self.GL
  File "/Users/jbongard/anaconda3/envs/public-robodiff/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 15, in __get__
    value = self.fget( obj )
  File "/Users/jbongard/anaconda3/envs/public-robodiff/lib/python3.7/site-packages/OpenGL/platform/darwin.py", line 41, in GL
    raise ImportError("Unable to load OpenGL library", *err.args)
ImportError: ('Unable to load OpenGL library', "dlopen(OpenGL, 0x000A): tried: 'OpenGL' (no such file), '/System/Volumes/Preboot/Cryptexes/OSOpenGL' (no such file), '/Users/jbongard/anaconda3/envs/public-robodiff/lib/python3.7/lib-dynload/../../OpenGL' (no such file), '/Users/jbongard/anaconda3/envs/public-robodiff/bin/../lib/OpenGL' (no such file), '/usr/lib/OpenGL' (no such file, not in dyld cache), 'OpenGL' (no such file), '/usr/local/lib/OpenGL' (no such file), '/usr/lib/OpenGL' (no such file, not in dyld cache)", 'OpenGL', None)

**Comment by CappuccinoPanda** [comment]
If you have Xcode installed on MacOS, I've been able to patch this before by editing line 79-80 of ctypesloader.py.

If anyone knows a cleaner solution, please let us know. 😄 

From:
```python
fullName = util.find_library( name )
```
To:
```python
if name == "OpenGL":
	fullName = '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/OpenGL'
