### ISSUE TITLE
Ubuntu 18.04 Runtime Errors

### ISSUE THREAD

**Issue by jrieffel** [robodiff/robodiff#3]
I followed the `README.md` instructions, and got as far as running the demo, but got an error, shown below:

```
(public-robodiff) rieffelj@Mille-Feuille:~/src/robodiff$ python main.py -vv --gui --cpu
[Taichi] mode=release
[Taichi] preparing sandbox at /tmp/taichi-c3wd8i5k
[Taichi] version 0.7.16, llvm 10.0.0, commit bca037cf, linux, python 3.7.15
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    import robodiff_startup as dipv
  File "/home/rieffelj/src/robodiff/robodiff_startup.py", line 15, in <module>
    from visualization.utils import visualization_callback
  File "/home/rieffelj/src/robodiff/visualization/utils.py", line 8, in <module>
    from visualization.visualizer_gl_taichi_free import visualize
  File "/home/rieffelj/src/robodiff/visualization/visualizer_gl_taichi_free.py", line 8, in <module>
    from glumpy.transforms.viewport import Viewport
  File "/home/rieffelj/anaconda3/envs/public-robodiff/lib/python3.7/site-packages/glumpy/__init__.py", line 7, in <module>
    from . import app
  File "/home/rieffelj/anaconda3/envs/public-robodiff/lib/python3.7/site-packages/glumpy/app/__init__.py", line 14, in <module>
    from glumpy import gl
  File "/home/rieffelj/anaconda3/envs/public-robodiff/lib/python3.7/site-packages/glumpy/gl.py", line 38, in <module>
    from OpenGL.GL import *
  File "/home/rieffelj/anaconda3/envs/public-robodiff/lib/python3.7/site-packages/OpenGL/GL/__init__.py", line 4, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/home/rieffelj/anaconda3/envs/public-robodiff/lib/python3.7/site-packages/OpenGL/GL/VERSION/GL_1_1.py", line 14, in <module>
    from OpenGL.raw.GL.VERSION.GL_1_1 import *
  File "/home/rieffelj/anaconda3/envs/public-robodiff/lib/python3.7/site-packages/OpenGL/raw/GL/VERSION/GL_1_1.py", line 7, in <module>
    from OpenGL.raw.GL import _errors
  File "/home/rieffelj/anaconda3/envs/public-robodiff/lib/python3.7/site-packages/OpenGL/raw/GL/_errors.py", line 4, in <module>
    _error_checker = _ErrorChecker( _p, _p.GL.glGetError )
AttributeError: 'NoneType' object has no attribute 'glGetError'
```

Even when I asked nicely with sudo I got a different error:

```
(public-robodiff) rieffelj@Mille-Feuille:~/src/robodiff$ sudo python main.py -vv --gui --cpu
[sudo] password for rieffelj: 
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    import robodiff_startup as dipv
  File "/home/rieffelj/src/robodiff/robodiff_startup.py", line 184
    **morph_backwards_grads, **act_backwards_grads
                           ^
SyntaxError: invalid syntax

```

Would appreciate your guidance!

**Comment by ms903** [comment]
try `pip install --upgrade pyrender`
